apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pvc-prometheus-alermanager"
  labels:
      name: "pvc-prometheus-alertmanager"
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: prome-prometheus-alertmanager
    namespace: agents
  awsElasticBlockStore: 
    fsType: "ext4"
    volumeID: {{ default "" .Values.alertmanager.ebsPersistentVolumeID | quote }} 
