apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pvc-prometheus"
  labels:
    name: "pvc-prometheus"
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore: 
    fsType: "ext4"
    volumeID: {{ default "" .Values.server.ebsPersistentVolumeID | quote }}
