version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: minhnh/docker-helm-node:0.1
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: coverage/lcov.info

workflows:
  version: 2
  build:
    jobs:
      - test
