{{- if .Values.textFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-textfiles
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- range $key, $val := .Values.textFiles }}
  {{ $key }}: {{ (print $val) | quote }}
  {{- end }}
{{- end }}

