{{- if .Values.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-files
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $val := .Values.files }}
  {{ $key }}: {{ (print $val) | quote }}
  {{- end }}
{{- end }}
