apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ (print $val) | b64enc | quote }}
  {{- end }}
