apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "process-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    helm.sh/chart: {{ include "process-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml:
{{ toYaml .Values.config_file | indent 4 }}

