apiVersion: v1
kind: Service
metadata:
  name: {{ include "process-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    helm.sh/chart: {{ include "process-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
