{{- if .Values.config -}}
apiVersion: v1
data:
  alerta-config: {{ .Values.config | quote }}
kind: ConfigMap
metadata:
  name: {{ include "alerta.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "alerta.name" . }}
    helm.sh/chart: {{ include "alerta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
