apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alerta.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alerta.name" . }}
    helm.sh/chart: {{ include "alerta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alerta.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alerta.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: alerta-web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.config }}
        volumeMounts:
        - name: config
          subPath: alerta-config.conf
          mountPath: /app/alertad.conf
        {{- end }}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - secretRef:
            name: {{ include "alerta.fullname" . }}-secrets
      {{- if .Values.config }}
      volumes:
        - name: config
          configMap:
            name: {{ include "alerta.fullname" . }}-configmap
            items:
              - key: alerta-config
                path: alerta-config.conf
      {{- end }}
