{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alerta.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "alerta.name" . }}
    helm.sh/chart: {{ include "alerta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ (print $val) | b64enc | quote }}
  {{- end }}
{{- end }}
