apiVersion: v1
kind: Service
metadata:
  name: {{ include "alerta.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alerta.name" . }}
    helm.sh/chart: {{ include "alerta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "alerta.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
