{{- $top_scope := . -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default 1 .Values.config.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.app.name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      terminationGracePeriodSeconds: 60
      {{- if .Values.files }}
      volumes:
      - name: "kubestore"
        secret:
          secretName: "{{ .Values.app.name }}-files"
      {{- end }}
      containers:
      - name: web
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin
        - containerPort: 7946
          name: cluster
        - containerPort: 7946
          protocol: UDP
          name: cluster-udp
        {{- if .Values.files }}
        volumeMounts:
        - name: "kubestore"
          mountPath: "/etc/kubestore"
          readOnly: true
        {{- end }}
        resources:
          requests:
            cpu: "{{ .Values.config.cpu_request }}"
            memory: "{{ .Values.config.memory_request }}"
        {{- include "image_labels" $top_scope | indent 8 }}
        {{- include "env_labels" $top_scope | indent 8 }}
      {{- range $worker_name, $worker_command := .Values.app.workers }}
      {{- if $worker_command }}
      - name: {{ $worker_name }}
        {{- include "command_labels" $worker_command | indent 8 }}
        {{- include "image_labels" $top_scope | indent 8 }}
        {{- include "env_labels" $top_scope | indent 8 }}
      {{- end }}
      {{- end }}
